name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - racy

jobs:
  bench:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: funnel
        run: cd tachyobench; cargo run --release funnel-chenal; cargo run --release funnel-crossfire; pinball-tachyonix
      - name: pinball
        run: cd tachyobench; cargo run --release pinball-chenal; cargo run --release pinball-crossfire; pinball-tachyonix
      - name: seq
        run: cd bench; cargo bench ".*/.*/seq/msg_size=1$" -- --quick
      - name: blocking spsc
        run: cd bench; cargo bench ".*/.*/blocking/msg_size=1/senders=1/receivers=1/capacity=16384" -- --quick
      - name: blocking mpsc
        run: cd bench; cargo bench ".*/.*/blocking/msg_size=1/senders=4/receivers=1/capacity=16384" -- --quick

