name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [--no-default-features, --all-features]
    steps:
      - uses: actions/checkout@v6
      - name: rustfmt
        run: cargo fmt -- --check --config "unstable_features=true,imports_granularity=Crate,group_imports=StdExternalCrate,format_code_in_doc_comments=true"
      - name: clippy
        run: cargo clippy ${{ matrix.features }} --all-targets -- -D warnings
      - name: test
        run: cargo test ${{ matrix.features }}
      - name: check doc
        if: matrix.features == '--all-features'
        run: cargo doc ${{ matrix.features }}
        env:
          RUSTDOCFLAGS: "-Dwarnings"

  loom:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [mpmc_array, mpsc_array, spmc_array, spsc_array]
    steps:
      - uses: actions/checkout@v6
      - name: loom
        run: cargo test --features blocking --release --test ${{ matrix.test }} loom_
        env:
          LOOM_MAX_PREEMPTIONS: 2
          RUSTFLAGS: --cfg=loom --cfg=racy_test

  compute-miri-seeds:
    runs-on: ubuntu-latest
    outputs:
      seeds: ${{ steps.compute-seeds.outputs.seeds }}
    steps:
      - id: compute-seeds
        run: python3 -c "print('seeds=' + str([f'{i}..{i+$TOTAL//$RUNNERS}' for i in range(0,$TOTAL,$TOTAL//$RUNNERS)]))" >> $GITHUB_OUTPUT
        env:
          TOTAL: 2048
          RUNNERS: 16

  miri:
    needs: [test, compute-miri-seeds]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [mpmc_array, mpsc_array, spmc_array, spsc_array]
        seeds: ${{ fromJson(needs.compute-miri-seeds.outputs.seeds) }}
    steps:
      - uses: actions/checkout@v6
      - name: install miri
        run: rustup install nightly && rustup +nightly component add miri
      - name: miri
        run: cargo +nightly miri test --all-features --test ${{ matrix.test }}
        env:
          RUSTFLAGS: --cfg=racy_test
          MIRIFLAGS: -Zmiri-many-seeds=${{ matrix.seeds }} -Zmiri-compare-exchange-weak-failure-rate=0
